name: my-first-actions

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
  MY_VARIABLE: "This is a variable"

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x]

        steps:
          - uses: actions/checkout@v2

          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}

          - name: Afficher un message
            run: echo "Hello, GitHub Actions !"

          - name: Afficher la variable d'environnement
            run: echo "${{ env.MY_VARIABLE }}"

          - name: Afficher le secret
            run: echo "${{ secrets.MY_SECRET }}"

          - name: Créer le fichier hello.txt
            run: echo "Hello world" > hello.txt

          - name: Afficher le contenu de hello.txt
            run: cat hello.txt

          - name: Installer les dépendances
            run: npm i

          - name: Exécuter les test
            run: npm test

    second_job:
        runs-on: ubuntu-latest

        needs: build

        steps:
          - name: Afficher un message dans le second job
            run: echo "Second job running"
