name: my-first-actions

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
  MY_VARIABLE: "This is a variable"

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x]

        steps:
          - uses: actions/checkout@v2

          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}

          - name: Installer les dépendances
            run: npm i

          - name: Afficher un message
            run: echo "Hello, GitHub Actions !"

          - name: Afficher la variable d'environnement
            run: echo "${{ env.MY_VARIABLE }}"
